### PR TITLE
Add a link from each CI badge to the corresponding section in the README

### PR DESCRIPTION
**Pull request by mwouts**
Hi @goanpeca , I was glad to see that you've been working on `mamba` support!

What would you think of adding these links? With this, clicking on a badge (other than 'Linting') will get the user to the corresponding section in the README.

### CODE REVIEW

**Comment by bollwyvl** [comment]
Thanks, this is helpful. It's getting to be a lot! Maybe a (literal) table
of contents, with the name as a link to the readme, and smaller ci badges
linking to that job, would be more digestible still?

**Comment by mwouts** [comment]
Yes, possibly! Are you thinking of something like this?

| | |
| --- | --- |
| [Example 1: Basic usage](#example-1-basic-usage) | Example 1: Basic usage |
| [Example 2: Other shells](#example-2-other-shells) | Example 2: Other shells |
| [Example 3: Other options](#example-3-other-options) | Example 3: Other options |
| [Example 4: Channels](#example-4-conda-options) | Example 4: Channels |
| [Example 5: Custom installer](#example-5-custom-installer) | Example 5: Custom installer |
| [Example 6: Mamba](#example-6-mamba) | Example 6: Mamba |
| [Caching Example](#caching) | Caching Example |
| Linting | Linting |

**Comment by bollwyvl** [comment]
Yeah, personally i find that easier to read. We might just want an even shorter badge, e.g. 

[![Basic Usage][ex1-badge]][ex1]

[ex1]: https://github.com/conda-incubator/setup-miniconda/actions?query=branch%3Amaster
[ex1-badge]: https://img.shields.io/github/workflow/status/conda-incubator/setup-miniconda/Example%201:%20Basic%20usage/master

from:
```md
[![Basic Usage Build Status][ex1-badge]][ex1]

[ex1]: https://github.com/conda-incubator/setup-miniconda/actions?query=branch%3Amaster
[ex1-badge]: https://img.shields.io/github/workflow/status/conda-incubator/setup-miniconda/Example%201:%20Basic%20usage/master
```

**Comment by bollwyvl** [comment]
Perhaps a way to get even more compactness would be to use the custom shields.io URL, and drop the `Example X` from each of the labels?

**Comment by goanpeca** [comment]
Hi @mwouts, thanks for working on this.


See https://github.com/conda-incubator/setup-miniconda/pull/82

**Comment by bollwyvl** [comment]
We adapted and updated this over on #153, thanks again and sorry for the delay. Feel free to open a new issue if the current setup isn't too your liking!!

**Pull request closed without merging**
