### PR TITLE
Issue #208 - Do not move non-existing files

### PR DESCRIPTION
**Pull request by martin-g**
This is a small improvement to not try to move .bashrc into .profile if
.bashrc does not even exists.

This is needed for non-ephemeral self-hosted Github Actions runners
where one VM could run multiple runners.

There is still a chance another GHA runner to move the file between the `existsSync` and `io.mv` calls.

### CODE REVIEW

**Comment by martin-g** [comment]
> There is still a chance another GHA runner to move the file between the `existsSync` and `io.mv` calls.

I don't see a solution for this problem except stop using the shell rc files completely.

Would it be possible to just issue `conda activate XYZ` when/where needed instead of adding `bashExtraText` to `~/.profile` ?

**Comment by goanpeca** [comment]
>Would it be possible to just issue conda activate XYZ when/where needed instead of adding bashExtraText to ~/.profile ?

Unbfortunately it will not work :-\

**Review by goanpeca — APPROVED** [review]
LGTM Thanks!

**Comment by goanpeca** [comment]
Sorry for the delays! And thanks again for your contribution 🚀

**Pull request merged**
