### PR TITLE
Copy channels before reversing

### LINKED ISSUE #160: Channel priority changed in 2.1.0 release
Distributed's CI specifies the conda channels to use inside a [conda environment file](https://github.com/dask/distributed/blob/25a2867e8e950d9cb51b071337ffc43ddaf0bb52/continuous_integration/environment-3.8.yaml) where we prefer to use conda-forge where possible and fallback to using defaults when needed.

After the `setup-miniconda` 2.1.0 release we started observing many more packages being installed from defaults instead of conda-forge (see the links below which compare the packages installed using `setup-miniconda=2.0.1` and `setup-miniconda=2.1.0`). Was this an intentional change that requires users to make changes to our GitHub actions workflow? 

- [`conda list` with `setup-miniconda=2.0.1`](https://github.com/dask/distributed/pull/4646/checks?check_run_id=2220556762#step:7:7)
- [`conda list` with `setup-miniconda=2.1.0`](https://github.com/dask/distributed/runs/2220484541#step:7:7)

### PR DESCRIPTION
**Pull request by bollwyvl**
- fixes #160
- [x] use `.slice` to copy channels before reversing
- [x] updates `package-lock.json` after installing from fresh environment
- [x] add "typical" channel line-up to example environment 
- [ ] add test of `environment-patched.yml`? Hoist to output?

### CODE REVIEW

**Comment by bollwyvl** [comment]
By _inspection_, this is fixing the issue:
https://github.com/conda-incubator/setup-miniconda/pull/161/checks?check_run_id=2222447371#step:3:257

the order is as set in the original yaml. I don't know how to _simply_ retrieve the logs from within the action (if that's even possible), but otherwise this is ready for review.

**Comment by bollwyvl** [comment]
I guess we could hoist the "effective used environment" to an action output...

**Comment by jaimergp** [comment]
So what was the issue? `.reverse()` acting in place instead of returning a reversed "view" and that can leave the list of channel in the wrong state for the next operation?

**Comment by bollwyvl** [comment]
> acting in place instead of returning a reversed "view"

right, gory details on #160

**Comment by jaimergp** [comment]
Huh, that's surprising indeed, at least coming from the Python world. If that's the case and this fixes the misbehavior, this LGTM.

How would you like for the right behavior? Diffing `conda list`s?

**Comment by bollwyvl** [comment]
Yeah dunno, re: testing.... Maybe something in conda-meta/history?

**Comment by goanpeca** [comment]
Looks good @bollwyvl 

Should I make a 2.1.1 release?

**Comment by bollwyvl** [comment]
Good by me to release unless we can figure out what the other fresh issue
is regarding python-version... #158... Might be a change, but not
necessarily a _bug_ whereas this definitely was.

**Pull request merged**
