### PR TITLE
Fix CI

### PR DESCRIPTION
**Pull request by dbast**
Includes:
* Run `npm run format` + `npm run build` (first commit)
* Fix Example 6 + 10 (second commit)

Fixes the lint workflow + failing example workflows.

### CODE REVIEW

**Comment by goanpeca** [comment]
@dbast thanks for the PR. 2 things:
- Do you have the latest develop?
- Could you please open a PR from a branch in a fork, or from a separate branch within the same repo?

Thanks :)

**Comment by dbast** [comment]
@goanpeca That exactly what I did.. the PR is from a branch in my fork and one single commit head of current develop branch.... trying to get all of the workflow green :) ... will require more commit.

**Comment by goanpeca** [comment]
😅  @dbast what I meant to say is to have a branch name on your fork that does not have the same name as the target branch 😄 

Since all the develop goes to the develop branch, is just better to keep things tidy

So that instead of this

`conda-incubator:develop <- dbast:develop`

It is more like this

`conda-incubator:develop <- dbast:fix-ci`

**Comment by dbast** [comment]
yay... all workflows green on develop branch!

@conda-incubator/setup-miniconda ready for review/merge :)

**Pull request merged**
