### PR TITLE
set unsatisfiable_hints=false for conda only

### PR DESCRIPTION
**Pull request by jaimergp**
Comes from #192

### CODE REVIEW

**Comment by jaimergp** [comment]
Huh, looks like there's some kind of non-determinism there... The "cleaner implementation" is faulty, so ignore that one.

The two commits there fail in different tests that, otherwise, would pass with an unset `unsatisfiable_hints`. I will look into this.

**Comment by jaimergp** [comment]
Yes, this is known and needs to be fixed at the `conda` level: https://github.com/conda/conda/issues/9862

**Comment by goanpeca** [comment]
@jaimergp could you update with the latest `develop` branch ?

**Comment by jaimergp** [comment]
Oops, this should have been closed some time ago. Enabling that flag makes conda change behaviour, resulting in unsatisfiable solves (but it should be solved!).

**Pull request closed without merging**
