### PR TITLE
Table with links to sections and CI builds

### PR DESCRIPTION
**Pull request by mwouts**
This is an alternative to #82. In this version the TOC appears as a table, see https://github.com/mwouts/setup-miniconda/blob/toc_as_table/README.md

### CODE REVIEW

**Comment by bollwyvl** [comment]
Which one do you like better, now that you're looking at them?

**Comment by mwouts** [comment]
I think I prefer #82, as the badges are more 'compact', see https://github.com/mwouts/setup-miniconda/blob/master/README.md
Don't you think that the table is a bit big? Maybe it's better if the reader does not need to scroll to read the first paragraph.
Anyway that's just my preference, feel free to choose whichever you like most!

**Comment by bollwyvl** [comment]
It is tall, and will get taller... while it might fit today as a wide table, scrolling horizontally is an even worse user experience, for sure. My issue with the super-long-words-in-a-picture is it is very small text... and the `Example X: ` prefix adds almost no information, but I don't think we should change the names at this point. 

Let's close this, unless you want to try anything else, and concentrate on #82...

**Comment by goanpeca** [comment]
Hello @mwouts, thanks for working on this, and sorry for the delays.

> In this version the TOC appears as a table, see

I think I actually like this version better, as indeed it works as a TOC and is easier to read vertically, than horizontally with badges of varying size. It does take more vertical space, but I think it helps with guiding users to an specific section in the README.


Thoughts?

**Comment by mwouts** [comment]
Hi @goanpeca , well the table version is longer for sure, but you're right, it makes it more explicit that the left entries are links to the sections.

Personally I'm good with any version that lets the user go to the matching paragraph! This means either
- #82 (but we lose the link to the CI)
- This one, #86 
- Or even a simple table of contents separated from the CI statuses. You can generate the TOC simply by copy pasting the README at https://github.com/luciopaiva/markdown-toc . Maybe that form of TOC would be simpler to maintain?

**Comment by bollwyvl** [comment]
We adapted and updated this over on #153, thanks again and sorry for the delay. Feel free to open a new issue if the current setup isn't too your liking!!

**Pull request closed without merging**
