### PR TITLE
Fix typo “enviroment”

### PR DESCRIPTION
**Pull request by 0x2b3bfa0**

### CODE REVIEW

**Review by mattwthompson — APPROVED** [review]
LGTM, thanks.

Are we merging stuff like this into `main` or `develop`?

**Comment by goanpeca** [comment]
develop :)

**Comment by mattwthompson** [comment]
Based on the merge conflict, it looks like this has [already been fixed](https://github.com/conda-incubator/setup-miniconda/blob/130c02129957f2c650468626752fd712dc21dbbf/src/setup.ts) in `develop` via #187.

Do we have a process for moving things into `main` and releases? That typo fix is about a year and a half old, so we should probably get it out into the world soon 🙂

**Comment by 0x2b3bfa0** [comment]
Already fixed on the `develop` branch, closing unmerged as a duplicate of https://github.com/conda-incubator/setup-miniconda/commit/8ca9e40cc6af21c75a0d82fde604ad61fb01cf49 🙈

**Pull request closed without merging**
