### PR TITLE
Fixes #166: Error on miniconda-version *not* specified instead of when it *is* specified.

### LINKED ISSUE #166: Still having errors with 32-bit miniconda setups
From [here](https://github.com/ktbarrett/find_libpython/pull/13/checks?check_run_id=2221834708#step:3:10). I am specifying `miniconda-version` and still get errors. The following line is to blame (I think, I don't know JS), it seems that it should check if miniconda-version is **not** set and architecture != x64, based on the error message.
https://github.com/conda-incubator/setup-miniconda/blob/35d1405e78aa3f784fe3ce9a2eb378d5eeb62169/src/input.ts#L61-L63

### PR DESCRIPTION
**Pull request by chrisjbillington**
A simple fix to what appeared to be a simple bug.

Raise an error if on non-x64 architectures, `miniconda-version` is *not* specified, instead of when it *is* specified.

### CODE REVIEW

**Comment by jaimergp** [comment]
Thanks! Do we need a test for this or is it enough with what we have so far?

**Comment by chrisjbillington** [comment]
I thought I'd add that this does not fix the more general problem of old conda builds (many of which are 32-bit) being unsupported - ongoing attempts to address that issue are in #168.

However, some 32-bit builds, namely Windows, [have recent relases](https://repo.anaconda.com/miniconda/):

Miniconda3-latest-Windows-x86.exe | 55.3M | 2021-07-21 11:05:08 | a082be7ef6dd4f14b974dab2d78c5693
-- | -- | -- | --

So this fix restores the ability to use them, at least.

**Comment by ktbarrett** [comment]
I think tests would show that 32 bit support is still not quite there, but I don't think that fact should block this obvious bugfix from coming in.

**Review by jaimergp — APPROVED** [review]
LGTM but I'd have @bollwyvl have a look too!

**Comment by bollwyvl** [comment]
Yep, the fix looks good. As it was a bug, we probably do need a test, which can then also be used for documentation purposes in the README.

Also it probably needs to have the build re-run to update the transpiled assets

**Comment by jaimergp** [comment]
This seems to be successfully using x86-latest on Windows now and failing (on purpose) on Ubuntu/Mac. I did this because latest x86-Ubuntu predates 4.6, which is the oldest we are supporting currently.

**Comment by chrisjbillington** [comment]
Thanks very much for fleshing this out @jaimergp! That one-character change was getting close to the limits of what I might be able to do with javascript. Really appreciate it!

**Comment by ktbarrett** [comment]
Any status on this?

**Comment by jaimergp** [comment]
Let's ping core :) @conda-incubator/setup-miniconda

**Comment by ktbarrett** [comment]
3 months later this has been approved, but still hasn't been merged. What gives?

**Comment by goanpeca** [comment]
Whoops, this fell under the cracks! Sorry

Merging˜!

**Pull request merged**
