### PR TITLE
Fix logic in 32-bit architecture check

### LINKED ISSUE #166: Still having errors with 32-bit miniconda setups
From [here](https://github.com/ktbarrett/find_libpython/pull/13/checks?check_run_id=2221834708#step:3:10). I am specifying `miniconda-version` and still get errors. The following line is to blame (I think, I don't know JS), it seems that it should check if miniconda-version is **not** set and architecture != x64, based on the error message.
https://github.com/conda-incubator/setup-miniconda/blob/35d1405e78aa3f784fe3ce9a2eb378d5eeb62169/src/input.ts#L61-L63

### PR DESCRIPTION
**Pull request by ktbarrett**
Closes #166.

### CODE REVIEW

**Comment by goanpeca** [comment]
Thanks for working on this @ktbarrett 

Is there a way we can test this by updating some of the examples that run on CI ?

**Comment by ktbarrett** [comment]
@goanpeca I'll look into adding some CI checks for other architectures. I see you have the checks oriented around the README examples, would you like some additional documentation added to the README?

**Comment by goanpeca** [comment]
Absolutely :)

We will move that to a docs site eventually

**Comment by goanpeca** [comment]
Also could you point this PR against the develop branch? And not the master one?

Thanks!

**Comment by chrisjbillington** [comment]
Any chance of getting this merged soon?

**Comment by ktbarrett** [comment]
Apparently I don't know anything.

**Comment by goanpeca** [comment]
@ktbarrett thanks for working on this!

>Apparently I don't know anything.

You need to compile the TS file into JS to be able to see any actual changes run on CI. See the the steps here:

https://github.com/conda-incubator/setup-miniconda/blob/master/CONTRIBUTING.md

**Comment by goanpeca** [comment]
https://github.com/conda-incubator/setup-miniconda/pull/168/checks?check_run_id=2319868097#step:3:19

Screen Shot 2021-04-11 at 8 39 54 PM

**Comment by goanpeca** [comment]
@ktbarrett since the 32bit installers are old, they might be using and old conda by default that does not provide the conda executable inside a `condabin` folder, but on a `bin` folder.

`/usr/share/miniconda3/condabin/conda` you will need to update the code accordingly where we define where to look for conda executables.

Thanks!

**Comment by goanpeca** [comment]
@ktbarrett its turtles all the way down, now you see why adding support for this was on hold :) 

So `conda init` is a command we rely on for correctly initializing conda, so in the 32 bit installer the conda that comes bundled does not provide that option, which means we wont be able to properly activate environments :-|

**Comment by goanpeca** [comment]
Ideas @bollwyvl ?

**Comment by jaimergp** [comment]
I think the first version to offer `conda init` and `$CONDA_ROOT/condabin` was 4.6.0. At least it looks like that from the [release notes](https://docs.conda.io/projects/conda/en/latest/release-notes.html#id162).

We can check which version is trying to get installed and error out if <4.6. Maybe there are other rough edges down there, but we can start with this.

cc @chrisjbillington @ktbarrett

**Comment by ktbarrett** [comment]
closing in favor of #189.

**Pull request closed without merging**
