### PR TITLE
Resolve dependencies and rebuild, squash warnings

### LINKED ISSUE #78: Getting deprecation warnings for "add-path" and "set-env"
Thanks for the nice project! Seems to work rather nicely - except that apart from warnings regarding duplicate channels that have already been reported (#57), I'm also getting rather worrying warnings from GitHub Actions regarding the use of `add-path` and `set-env`:

```console
# Locating Miniconda...
#######################

/usr/share/miniconda

# Setup environment variables...
################################

Add "/usr/share/miniconda/condabin" to PATH
Warning: The `add-path` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
/usr/share/miniconda/condabin/conda config --add pkgs_dirs /home/runner/conda_pkgs_dir
Warning: The `set-env` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
```

My workflow config:
```yaml
on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      matrix:
        python-version: [3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Setup Conda environment with Python ${{ matrix.python-version }}
      uses: conda-incubator/setup-miniconda@v1.7.0
      with:
        activate-environment: install-deps
        auto-activate-base: false
        auto-update-conda: true
        environment-file: environment.yml
        python-version: ${{ matrix.python-version }}
  # ... 
```

Apparently this is related to a mild security vulnerability and the deprecation warnings have only been added a couple of days ago. See this blog post for more info, including how to mitigate the issue: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

### PR DESCRIPTION
**Pull request by bollwyvl**
This resolves the dependencies updates suggested by #77 and #69, but also runs the build so might be simpler than taking those.

This should _also_ fix #78 (once released).

### CODE REVIEW

**Comment by bollwyvl** [comment]
The upgrade reveals some new warnings:

https://github.com/conda-incubator/setup-miniconda/actions/runs/291485813

```
Please run using "bash" or "sh", but not "." or "source"\n/home/runner/work/_temp/47b7cea6-d0a4-4996-8834-c36d4302b2f5: line 13: return: can only `return' from a function or sourced script

Please run using "bash" or "sh", but not "." or "source"\n
```

as well as of course the conda upgrade... will take a look into squashing them...

**Comment by bollwyvl** [comment]
looks like that's just some juiced-up warnings... the only thing i've seen is to redirect the output, e.g. `bash miniconda.sh > /tmp/installer-output`. The installer output is not very interesting, anyway, so maybe we only show it in case of error?

**Comment by bollwyvl** [comment]
ah, i see `execute` has an error swallowing mechanism, will add to that...

**Review by goanpeca — APPROVED** [review]
Looks great, thanks @bollwyvl

**Comment by goanpeca** [comment]
Are we good to merge after tests pass?

**Comment by bollwyvl** [comment]
I'd like to get all the errors we know about today squashed, since that's what people see...

**Comment by bollwyvl** [comment]
Ok, I have the ones from https://github.com/conda-incubator/setup-miniconda/pull/79#issuecomment-704279792 squared away.

We just need to pick (some) approaches for the conda update notify, happy to do them here!

**Comment by goanpeca** [comment]
Ping me or merge when ready @bollwyvl the overall approach looks good, so thanks again :-)

**Comment by bollwyvl** [comment]
@goanpeca Ok, the bootstrap `condarc` does the trick. It gets overwritten if the user specifies a conda file, which is fine, i think, at least they will know it can be used, and can control. I'd say this is ready to go!

**Comment by bollwyvl** [comment]
Pushed for https://github.com/conda-incubator/setup-miniconda/pull/79#issuecomment-704334079 (_Other Shells_ should have no warnings)

**Comment by bollwyvl** [comment]
Yep, that did it: we're down to just first-party warnings, not planning to do anything else here...

**Comment by bollwyvl** [comment]
Hooray!

**Comment by bollwyvl** [comment]
So can this already be tested out, or do we need a release?

**Comment by bollwyvl** [comment]
Trying out `@master`, it looks like the explicit stuff was never tested on windows, and therefore doesn't work... sigh.

https://github.com/krassowski/jupyterlab-lsp/pull/348/checks?check_run_id=1216272360

**Pull request merged**
