### PR TITLE
Try to catch EnvironmentSectionNotValid

### LINKED ISSUE #93: Silent errors with faulty environment file
If a user provides an invalid YAML file (e.g. wrong section name), the action fails to update the environment with that file, but doesn't report the failure.

To reproduce, try using a YAML file like this:

```
name: test
channels:
  - conda-forge
  - defaults
requirements:
  - compilers
  - python
```

Note how I used `requirements` instead of `dependencies`. You will see this unreported error:

```
# Updating conda environment from yaml file...
##############################################

/usr/share/miniconda/condabin/conda env update --file devtools/conda-envs/test_env.yaml --name test

EnvironmentSectionNotValid: The following section on '/home/runner/work/yank/yank/devtools/conda-envs/test_env.yaml' is invalid and will be ignored:
 - requirements

#
# To activate this environment, use
#
#     $ conda activate test
#
# To deactivate an active environment, use
#
#     $ conda deactivate
```

[Example on a real log](https://github.com/choderalab/yank/pull/1244/checks?check_run_id=1399580088#step:4:782).

### PR DESCRIPTION
**Pull request by jaimergp**
Fixes #93

### CODE REVIEW

**Review by goanpeca — APPROVED** [review]
Looks good @jaimergp 

Thanks for looking into this!

How did you test it? We will need to add actual unit tests to this. (for a separate PR, no worries)

Any suggestions @bollwyvl ?

**Comment by jaimergp** [comment]
I didn't  and I don't know how to do it locally 😬  I can add the tests in this PR too, but I'll need some guidance. Where should I look?

**Comment by goanpeca** [comment]
>I didn't and I don't know how to do it locally

No worries I will setup something to get some basic testing setup for this locally. 

In the meantime maybe just create a new workflow that falis https://github.com/conda-incubator/setup-miniconda/blob/master/.github/workflows/example-1.yml if it fails then we are good :-p

**Comment by goanpeca** [comment]
@jaimergp for (github CI) security reasons, I think the new workflow will not run so I will merge, and please check again what happens on the actions that will run on master and open a new PR accordingly :-p 

Thanks again!

**Comment by goanpeca** [comment]
See https://github.com/conda-incubator/setup-miniconda/actions

**Comment by jaimergp** [comment]
Nop, it was a syntax error. I'll open a new one.

**Pull request merged**
