### PR TITLE
PR: Add conda channels option

### PR DESCRIPTION
**Pull request by goanpeca**
Related to #4

### CODE REVIEW

**Comment by goanpeca** [comment]
@dcdenu4 could you test this PR ?

You can use this branch as `goanpeca/setup-miniconda@enh/channels`

**Comment by dcdenu4** [comment]
@goanpeca I tested it on my simple use case and it appears to work properly and pull from the added channels. It looks like for `channels: conda-forge, anaconda` , the priority order is `anaconda`, then `conda-forge`. It's a little counter intuitive to me, as I would think the first thing I list has the greatest priority, but if it's documented well then it doesn't really matter. 

Thanks for this!

**Comment by goanpeca** [comment]
That order is weird indeed I think I have an issue there so that is not right.

I will need to look i to it then

**Comment by goanpeca** [comment]
Ok I knew that could be an issue https://zellwk.com/blog/async-await-in-loops/

I need to change to a normal for otherwise the order is not guaranteed.  

And I learned something new about Js :-p

**Comment by goanpeca** [comment]
@dcdenu4 fixed the issue now. It should be in the right order now!

**Comment by dcdenu4** [comment]
@goanpeca Just ran two tests and they both use the first channel in my list, `conda-forge` in my case. So this is expected and different than prior when it was using `anacaonda`, my 2nd specified channel. Looks good!

**Comment by goanpeca** [comment]
Thanks for testing @dcdenu4 making a release soon ;-)

**Pull request merged**
