### PR TITLE
add tests for mamba on windows and osx

### LINKED ISSUE #59: mamba on windows "mamba: command not found"
on a currently private repo I am trying to use mamba to build on mac/linux/windows but I am running into a command not found error on the windows worker, seems like mamba is not available even after successful install as show in the logs.

partial config:
```
test_runner:
    name: (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: ["3.8"]
    steps:
      - uses: actions/checkout@v2
      - name: setup miniconda
        uses: goanpeca/setup-miniconda@v1
        with:
          mamba-version: "*"
          python-version: ${{ matrix.python-version }}
          channels: conda-forge,defaults
          channel-priority: true
          activate-environment: pangeo_test
          auto-update-conda: true
          use-only-tar-bz2: true
      - name: conda info
        shell: bash -l {0}
        run: |
          conda info
      - name: mamba install packages
        shell: bash -l {0}
        run: mamba install ... (command not found error here)
```

### PR DESCRIPTION
**Pull request by jaimergp**
Trying to investigate and (hopefully) solve #59

### CODE REVIEW

**Comment by jaimergp** [comment]
Ok, I am not sure if this is going to be useful, but it's a way to fix the Mamba on Windows problem.

Basically, the issue was that most users will be calling Mamba from Bash, but on Windows `mamba install xxx` needs to be `mamba.bat install xxx`. I have added a forwarder script (on Windows only) that will [delegate](https://github.com/conda-incubator/setup-miniconda/pull/100/files#diff-5d1af95661c2f11542bf816c46ed8d5f2a014b5666437e05a9f8f00647bd7df1R862) `mamba` calls to `mamba.bat`.

**Comment by goanpeca** [comment]
Sounds good @jaimergp, now should `mamba` alone work on any other shell on windows?

**Comment by jaimergp** [comment]
Hopefully @goanpeca! Check this run: https://github.com/conda-incubator/setup-miniconda/pull/100/checks?check_run_id=1412239926

**Comment by goanpeca** [comment]
Ohhh lovely :) 

Merging then! Will cut a new release as soon as @bollwyvl finishes #98

**Pull request merged**
